php:
  build: .
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./www:/var/www/html
  links:
    - db

db:
  image: mysql:5.7
  volumes:
    - ./mysql:/docker-entrypoint-initdb.d
    - ./mysql/config:/etc/mysql/conf.d
    - persistent:/var/lib/mysql
  environment: 
    - MYSQL_DATABASE=teste
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_PASSWORD=root
  
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db:db

  ports:
    - 8000:80

  environment: 
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_PASSWORD=root
 